/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "/betterUnitDecimated_forExportNOHAT.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Head.geometry}
        material={materials.material_atlas_00002_1}
        position={[0, 2.709, 0]}
      />
    </group>
  );
}

useGLTF.preload("/betterUnitDecimated_forExportNOHAT.glb");