/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const absolutePath = "/src/assets/entities/UnitWithAtlasMaterial.glb"
const relativePath = "./UnitWithAtlasMaterial.glb"
const path = absolutePath


export let Model = (props) => {

  const { nodes, materials } = useGLTF(path);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Unit.geometry}
      />
    </group>
  )
}

useGLTF.preload(path);