/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const absolutePath = "/src/assets/entities/UnitWithAtlasMaterial.glb"
const relativePath = "./UnitWithAtlasMaterial.glb"
const path = absolutePath

export var Model = (props) => {
  const { nodes, materials } = useGLTF(path);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Unit.geometry}
        material={materials.material_atlas_00001_1}
      />
    </group>
  );
}

useGLTF.preload(path);